name: petid
description: Aplicativo para gerenciamento de prontuÃ¡rios de pets com biometria por focinho
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # HTTP
  http: ^1.2.0
  dio: ^5.4.0
  
  # State Management
  provider: ^6.1.1
  
  # Storage
  shared_preferences: ^2.2.2
  
  # UI
  cupertino_icons: ^1.0.6
  
  # Image & Camera
  image_picker: ^1.0.7
  camera: ^0.11.0+1
  
  # Forms & Validation
  flutter_form_builder: ^10.2.0
  form_builder_validators: ^11.2.0
  
  # UI Helpers
  flutter_svg: ^2.0.9
  
  # QR Code
  qr_flutter: ^4.1.0
  
  # Location
  geolocator: ^13.0.1
  
  # URL Launcher
  url_launcher: ^6.2.4
  
  # Firebase
  firebase_core: ^3.8.1
  firebase_messaging: ^15.1.6
  
  # Local Notifications
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

